/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.main;

import br.com.senac.db.ConnectionUtils;
import br.com.senac.db.ContatoDb;
import br.com.senac.model.Contato;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger.roliveira
 */
public class ListarContato extends javax.swing.JPanel {

    ContatoDb db;
    
    /**
     * Creates new form ListarContato
     */
    public ListarContato() {
        initComponents();
        this.db = new ContatoDb(new ConnectionUtils());
        popularContatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContatos = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("CADASTRO DE CONTATO");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("LISTA DE CONTATOS");

        tableContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "NOME", "DATA DE NASCIMENTO", "TELEFONE", "EMAIL", "DATA DE CADASTRO"
            }
        ));
        jScrollPane1.setViewportView(tableContatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void popularContatos(){
        List<Contato> lista = db.obterContatos();
        DefaultTableModel model = (DefaultTableModel) tableContatos.getModel();
        model.setRowCount(0);
        int size = lista.size();
        for (int i = 0; i < size; i++){
            Contato c = lista.get(i);
            if (c != null) {
                Object[] row = new Object[6];
                row[0] = c.getId();
                row[1] = c.getNome();
                row[2] = c.getDataNascimento();
                row[3] = c.getNumeroTelefone();
                row[4] = c.getEmail();
                row[5] = c.getDataCadastro().toString();
                model.addRow(row);                
            }            
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableContatos;
    // End of variables declaration//GEN-END:variables
}
